server:
  port: 8081

hexagonal:
  client:
    address:
      url: http://localhost:8082/addresses

spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/hexagonal?authSource=admin